sudo: required
language: cpp
dist: trusty
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -y -qq qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
- sudo apt-get install -y -qq qt5-default qttools5-dev-tools
- sudo apt-get install -y -qq libtag1-dev libasound2-dev libjack-jackd2-dev
script:
- qmake PiCasterQt.pro
- make
after_success:
- openssl aes-256-cbc -K $encrypted_e4a4a7968508_key -iv $encrypted_e4a4a7968508_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
services:
- docker
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
