name: picaster
version: '0.2-git'
summary: PiCaster, the podcast recorder, in a snap.
description: PiCaster is a podcast recording and streaming application, easy to use for beginners, but with enough functionality to suit the needs of intermediate or experienced podcasters.
grade: devel
confinement: devmode
base: core18

apps:
  picaster:
    command: desktop-launch $SNAP/usr/bin/picaster
    plugs: [home, unity7, network, network-bind, pulseaudio, gsettings, x11, desktop, desktop-legacy, opengl, removable-media, wayland]

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
  picaster:
    plugin: qmake
    source: ./
    build-packages:
      - qtbase5-dev
      - libtag1-dev
      - libasound2-dev
      - libjack-jackd2-dev
      - libavformat-dev
      - libavcodec-dev
      - libavresample-dev
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libasound2
      - libjack-jackd2-0
      - libtag1v5-vanilla
    after: [desktop-qt5]

