name: picaster
version: '0.2-git'
summary: PiCaster, the podcast recorder, in a snap.
description: PiCaster is a podcast recording and streaming application, easy to use for beginners, but with enough functionality to suit the needs of intermediate or experienced podcasters.
grade: devel
confinement: devmode
base: core18

apps:
  picaster:
    command: desktop-launch $SNAP/opt/picaster/bin/picaster
    plugs: [home, unity7, network, network-bind, pulseaudio, gsettings, x11, desktop, desktop-legacy, opengl, removable-media, wayland]

parts:
  picaster:
    plugin: qmake
    source: ./
    build-packages:
      - qtbase5-dev
      - libtag1-dev
      - libasound2-dev
      - libjack-jackd2-dev
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libasound2
      - libjack-jackd2-0
      - libtag1v5-vanilla
    after: [desktop-qt5]

